- name: Update language packs
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - language-pack-en
    - language-pack-ja
- name: Update locale
  command: update-locale LANG=en_US.UTF-8 
  changed_when: false
