- name: Get kernel release version
  shell: uname -r
  register: kernel_release
  changed_when: false
- name: Install linux image extra for aufs
  apt:
    name: "linux-image-extra-{{ kernel_release.stdout }}"
    state: latest
- name: Add gpg key for docker
  apt_key:
    keyserver: "hkp://p80.pool.sks-keyservers.net:80"
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present
- name: Set sources.list for docker
  template:
    dest: /etc/apt/sources.list.d/docker.list
    src: docker.list.j2
- include: update.yml
- name: Install docker engine
  apt:
    pkg: docker-engine
    state: latest
- name: Add user to docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
- name: Restart docker service
  service:
    name: docker
    enabled: yes
    state: restarted
  changed_when: false
