- name: Set temporary file path
  set_fact:
    download_path: /tmp/packer.zip
    install_path: /opt/packer/{{ packer_version }}
- name: Make directory for packer files
  file:
    name: "{{ install_path }}"
    state: directory
- name: Check packer version
  become: no
  command: packer version
  register: version
  failed_when: false
  changed_when: version.rc != 0
- name: Download packer .zip file
  when: version | changed
  get_url:
    url: https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip
    dest: "{{ download_path }}"
    sha256sum: "{{ packer_sha256sum }}"
- name: Unarchive packer
  when: version | changed
  unarchive:
    copy: no
    src: "{{ download_path }}"
    dest: "{{ install_path }}"
- name: Link packer commands
  file:
    state: link
    src: "{{ install_path }}/{{ item }}"
    dest: /usr/local/bin/{{ item }}
  with_items:
    - packer
    - packer-builder-amazon-chroot
    - packer-builder-amazon-ebs
    - packer-builder-amazon-instance
    - packer-builder-digitalocean
    - packer-builder-docker
    - packer-builder-file
    - packer-builder-googlecompute
    - packer-builder-null
    - packer-builder-openstack
    - packer-builder-parallels-iso
    - packer-builder-parallels-pvm
    - packer-builder-qemu
    - packer-builder-virtualbox-iso
    - packer-builder-virtualbox-ovf
    - packer-builder-vmware-iso
    - packer-builder-vmware-vmx
    - packer-post-processor-artifice
    - packer-post-processor-atlas
    - packer-post-processor-compress
    - packer-post-processor-docker-import
    - packer-post-processor-docker-push
    - packer-post-processor-docker-save
    - packer-post-processor-docker-tag
    - packer-post-processor-vagrant
    - packer-post-processor-vagrant-cloud
    - packer-post-processor-vsphere
    - packer-provisioner-ansible-local
    - packer-provisioner-chef-client
    - packer-provisioner-chef-solo
    - packer-provisioner-file
    - packer-provisioner-powershell
    - packer-provisioner-puppet-masterless
    - packer-provisioner-puppet-server
    - packer-provisioner-salt-masterless
    - packer-provisioner-shell
    - packer-provisioner-shell-local
    - packer-provisioner-windows-restart
    - packer-provisioner-windows-shell

