- name: Set temporary file path
  set_fact:
    download_path: /tmp/vagrant.deb
- name: Check vagrant version
  sudo: no
  command: vagrant --version
  register: version
  failed_when: false
  changed_when: version.rc != 0
- name: Download vagrant .deb file
  when: version | changed
  get_url:
    url: https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.deb
    dest: "{{ download_path }}"
    sha256sum: "{{ vagrant_sha256sum }}"
- name: Install vagrant from .deb file
  when: version | changed
  apt:
    deb: "{{ download_path }}"
- name: Update vagrant to latest by apt
  apt:
    pkg: vagrant
    state: latest
- name: Make directory for vagrant files
  sudo: no
  file:
    name: ~/vagrant
    owner: "{{ ansible_user_id }}"
    state: directory
