- name: Install php packages
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - php5
    - php5-cli
    - php5-common
    - php5-curl
    - php5-gd
    - php5-json
    - php5-mcrypt
    - php5-mysql
    - php5-pgsql
    - php5-sqlite
- include: composer.yml
- include: phpunit.yml
